### PR TITLE
Change prefix name

### PR DESCRIPTION
**Pull request by lilyminium**
The base prefix in a conda build.sh recipe is called PREFIX, so I changed this to HOLE_PREFIX to avoid confusion.

### CODE REVIEW

**Comment by ianmkenney** [comment]
@lilyminium I feel like changing the environment variable trades confusion in one context (conda-build) for confusion in another (building anywhere else). My general experience with building/installing says to just use either `PREFIX` or `INSTALL_PREFIX`. Presumably once the conda package is built there aren't going to be new ones made so this will only really affect maintainers of the conda package. That said, a `build.sh` that produces a working conda package is:

```bash
# compile hole with gfortran
cd ${SRC_DIR}/src
source ../source.apache
make
make PREFIX=${PREFIX} install
```

From the [documentation](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html), I think that the last line is probably clear enough. Are there any other concerns besides the potential confusions in the conda-build protocol?

**Comment by orbeckst** [comment]
I'd consider `PREFIX` to be the standard name in UNIX land when using `make`, `configure` etc. Given that HOLE really has nothing to do with conda & friends (unless you're @ianmkenney ) I'd leave it as is.

**Review by orbeckst — CHANGES_REQUESTED** [review]
@lilyminium , I'd prefer not making the proposed changes (reason below, as stated in comment) but if you have strong opinions on the matter please say so and I'll reconsider.

My suggestion is to close the PR without further action.

> I'd consider `PREFIX` to be the standard name in UNIX land when using make, configure etc. Given that HOLE really has nothing to do with conda & friends per se I'd leave it as is.

**Comment by lilyminium** [comment]
Sounds good -- closing now.

**Pull request closed without merging**
